version: "3.8"

services:
  spring-deploy:
    container_name: hms-deploy
    depends_on:
      - mysql
    image: hospital-management-system:0.0.1-SNAPSHOT
    ports:
      - 8080:8080

  mysql:
    container_name: mysql-db
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: